title: MABE
email: mabeBakery@gmail.com
baseurl: "" 
url: "" 
instagram: Сладкарска къща МАВЕ

# Build settings
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
